import { GoogleGenAI } from '@google/genai';
import { AuditResult, Lead, OutreachDraft } from '../types';
import { analyzeWithPageSpeed } from './pagespeed';
import { promises as dnsPromises } from 'dns';

async function verifyEmailDeliverability(email: string): Promise<boolean> {
  if (!email || typeof email !== 'string') return false;
  
  const trimmed = email.trim();
  if (trimmed === "") return false;

  // 1. Strict RFC 5322 regex pattern check
  const emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
  if (!emailRegex.test(trimmed)) {
    console.log(`❌ Regex Validation Failed for: "${trimmed}"`);
    return false;
  }

  const [localPart, domain] = trimmed.split('@');
  if (!localPart || !domain) return false;

  const lowercaseLocal = localPart.toLowerCase();
  const lowercaseDomain = domain.toLowerCase();

  // 2. Blacklisted/invalid keywords representing dummy / lazy data generated by AI
  const blacklistWords = [
    'example', 'test', 'dummy', 'placeholder', 'notfound', 'none', 'null', 
    'undefined', 'yourname', 'someone', 'fake', 'admin@domain', 'info@domain',
    'contact@domain', 'not_found', 'na@', 'n/a'
  ];

  for (const word of blacklistWords) {
    if (lowercaseLocal.includes(word) || lowercaseDomain.includes(word)) {
      console.log(`❌ Blacklisted Term / Lazy Placeholder Found: "${trimmed}"`);
      return false;
    }
  }

  // 3. Obvious dummy/placeholder domains
  const placeholderDomains = [
    'company.com', 'business.com', 'email.com', 'website.com', 
    'somedomain.com', 'yourdomain.com', 'gamil.com', 'gnail.com', 
    'yaho.com', 'hotail.com', 'example.org', 'example.net', 'test.com'
  ];
  if (placeholderDomains.includes(lowercaseDomain)) {
    console.log(`❌ Placeholder Domain Found: "${trimmed}"`);
    return false;
  }

  // 4. Lightweight DNS Verification for deliverability (MX Record Check)
  try {
    const mxRecords = await dnsPromises.resolveMx(lowercaseDomain);
    if (!mxRecords || mxRecords.length === 0) {
      console.log(`❌ No MX Records resolved for domain: "${lowercaseDomain}"`);
      return false;
    }
    console.log(`✅ MX Records resolved successfully for "${lowercaseDomain}"`);
    return true;
  } catch (err: any) {
    console.warn(`⚠️ DNS MX lookup failed for "${lowercaseDomain}": ${err.message}. Retrying with A-record check.`);
    // Fallback: Check if we can resolve A record for the domain (to avoid false negatives due to local environment or strict DNS configs)
    try {
      const addresses = await dnsPromises.resolve4(lowercaseDomain);
      if (addresses && addresses.length > 0) {
        console.log(`✅ A Records resolved successfully for "${lowercaseDomain}" (Fallback)`);
        return true;
      }
    } catch (dnsErr: any) {
      console.log(`❌ Domain resolution (MX & A) failed completely for: "${lowercaseDomain}". Domain does not exist.`);
      return false;
    }
    return false;
  }
}

async function generateAiContent(prompt: string, enableSearch = false): Promise<string> {
  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) throw new Error("GEMINI_API_KEY Missing");

    const ai = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
    const config: any = {};
    
    if (enableSearch) {
      config.tools = [{ googleSearch: {} }];
    } else {
      config.responseMimeType = "application/json";
    }

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config
    });

    return response.text || "{}";
  } catch (err: any) {
    console.error("Gemini API error inside generateAiContent:", err);
    console.log("Using primary backup AI service.");
    return await callLlamaFallback(prompt);
  }
}

async function callLlamaFallback(prompt: string): Promise<string> {
  const groqKey = process.env.GROQ_API_KEY || "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";
  const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${groqKey}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      model: "llama-3.3-70b-versatile",
      messages: [{ "role": "user", "content": prompt }],
      response_format: { type: "json_object" }
    })
  });

  if (!response.ok) {
    const errText = await response.text();
    console.error("Groq API Error:", errText);
    throw new Error(`Fallback AI failed: ${response.statusText}`);
  }

  const data = await response.json();
  return data.choices[0].message.content;
}

export async function analyzeWebsiteAndGenerateAudit(websiteUrl: string, category: string, rawPageText?: string): Promise<AuditResult> {
  const hasWebsite = websiteUrl && websiteUrl.trim() !== "";
  const pageSpeedData = hasWebsite ? await analyzeWithPageSpeed(websiteUrl) : null;
  
  const prompt = hasWebsite ? `
You are evaluating a website for a business in the category: ${category}.
URL: ${websiteUrl}
Real PageSpeed Mobile Score: ${pageSpeedData ? pageSpeedData.mobile_score : 'N/A (Estimate it)'}
Scraped Content Snippet: ${rawPageText || "N/A"}

Please perform a simulated technical and business audit based on the provided URL context and standard industry expectations for this type of business.
Determine if they typically need, or appear to lack:
- Online Booking / Admissions
- AI Chatbot
- Automation Features
- Customer Portal

Return exactly a JSON object matching this TypeScript interface:
{
  "ssl": boolean, "mobile_friendly": boolean, "responsive": boolean, "contact_form": boolean,
  "speed_score": number, "mobile_score": number,
  "seo_score": number, "accessibility_score": number,
  "online_booking": boolean, "online_admission": boolean, "customer_portal": boolean,
  "ai_chatbot": boolean, "automation_features": boolean,
  "overall_score": number,
  "issues_found": ["string array"],
  "recommendations": ["string array"]
}
` : `
You are evaluating a business in the category: ${category}.
This business currently DOES NOT HAVE A WEBSITE. They only operate offline or via basic social media.

Please perform a simulated business audit based on the fact that they have zero web presence.
Determine why they desperately need:
- A Professional Website
- Online Booking / Admissions
- AI Chatbot
- Automation Features
- Customer Portal

Return exactly a JSON object matching this TypeScript interface. Set all website-specific boolean flags (ssl, responsive) to false and scores to 0.
{
  "ssl": false, "mobile_friendly": false, "responsive": false, "contact_form": false,
  "speed_score": 0, "mobile_score": 0,
  "seo_score": 0, "accessibility_score": 0,
  "online_booking": false, "online_admission": false, "customer_portal": false,
  "ai_chatbot": false, "automation_features": false,
  "overall_score": 0,
  "issues_found": ["No professional website exists", "Missed online visibility", ...etc],
  "recommendations": ["Build a professional website", "Setup online booking", ...etc]
}
`;

  try {
    const text = await generateAiContent(prompt);
    let rawJson = text || "{}";
    if (rawJson.includes("\`\`\`json")) {
      rawJson = rawJson.replace(/\`\`\`json/g, "").replace(/\`\`\`/g, "").trim();
    }
    return JSON.parse(rawJson) as AuditResult;
  } catch (err) {
    console.error("Audit Generation Error:", err);
    throw new Error("Failed to generate audit via AI.");
  }
}

export async function generateOutreachProposal(lead: Lead, audit: AuditResult): Promise<OutreachDraft> {
  const hasWebsite = lead.website && lead.website.trim() !== "";
  const auditDetails = hasWebsite 
    ? `Audit Details (Score: ${audit.overall_score}/100):\nIssues: ${audit.issues_found.join(', ')}\nRecommendations: ${audit.recommendations.join(', ')}`
    : `Audit Details: The business currently has NO PROFESSIONAL WEBSITE.\nIssues: ${audit.issues_found.join(', ')}\nRecommendations: ${audit.recommendations.join(', ')}`;
  
  const pitchContext = hasWebsite 
    ? "You are pitching a website redesign and automation upgrade to a prospect who already has a website."
    : "You are pitching a brand new, highly professional website and automation system to a prospect who CURRENTLY DOES NOT HAVE A WEBSITE.";

  const prompt = `
You are Dharamveer, a Web Developer specializing in modern websites, automation systems, and digital platforms.
${pitchContext}
Lead details:
- Business: ${lead.business_name}
- Category: ${lead.category}
- City: ${lead.city}

${auditDetails}

Write a highly personalized, compelling, and professional cold email pitch addressed to the management of ${lead.business_name}.
Every email MUST be uniquely structured and freshly worded so it does not feel templated. Use varied greetings, opening hooks, and transitions.

IMPORTANT: You MUST dynamically incorporate their specific situation into the email body.
If they do not have a website, emphasize the massive lost opportunity and how a new modern website will bring them credibility and customers. If they have a website, explicitly mention the exact issues you found (e.g. mobile responsiveness, missing online booking, slow speed) and how you can fix them.

To ensure the email is highly scannable and professional, you MUST use HTML formatting effectively:
- Use <strong>bold text</strong> to highlight key metrics, specific missing features, and the primary benefits you offer.
- Use clean HTML bullet points (<ul><li>...</li></ul>) to clearly list out the exact issues/missing features in their current setup AND the specific advanced automation features you propose to solve them.

You MUST include this exact Portfolio & Previous Work section in your email:
<strong>Portfolio & Previous Work:</strong><br>
<ul>
  <li><a href="https://casaarthiai.in/">Casaarthi AI</a></li>
  <li><a href="https://cronbuilder-eight.vercel.app/">Cron Builder</a></li>
  <li><a href="https://fatooratools-olive.vercel.app/">Fatoora Tools</a></li>
  <li><a href="https://nzheatpumpguide.thakordharamveer.workers.dev/">NZ Heat Pump Guide</a></li>
  <li><a href="https://nzsolarguide.thakordharamveer.workers.dev/">NZ Solar Guide</a></li>
</ul>

Offer them a free prototype homepage evaluation.

Close the email professionally:
Warm Regards,<br>
<strong>Dharamveer</strong><br>
Web Developer<br>
Email: <a href="mailto:thakordharamveer@gmail.com">thakordharamveer@gmail.com</a><br><br>

DO NOT omit the "Portfolio & Previous Work" list. Write the body purely in HTML format.

Return exactly a JSON object matching this TypeScript interface:
{
  "subject": "The email subject line",
  "body": "The HTML formatted email body"
}
`;

  const text = await generateAiContent(prompt);
  let rawJson = text || "{}";
  if (rawJson.includes("\`\`\`json")) {
    rawJson = rawJson.replace(/\`\`\`json/g, "").replace(/\`\`\`/g, "").trim();
  }
  return JSON.parse(rawJson) as OutreachDraft;
}

export async function discoverLeadsWithGemini(category: string, city: string): Promise<Lead[]> {
  const prompt = `
You are a professional lead researcher executing on Google Search. Your absolute highest priority is ZERO email bounces. Every single email address you return must be 100% real, active, verified, and deliverable.

Your task is to find small-to-medium businesses in category: "${category}" and city: "${city}".
You must target up to 4 businesses in total, aiming for a 50/50 ratio:
- 2 businesses that ALREADY HAVE an existing, live website (upgrade / redesign pitch).
- 2 businesses that DO NOT HAVE an official website yet, but operate offline / via secondary socials like Facebook, Instagram, or Google Maps listing (new website creation pitch).

CRITICAL SEARCH & VERIFICATION WORKFLOW:
1. Candidate Search: Run search queries to identify local brick-and-mortar stores, offices, clinics, or schools in "${city}" for the category "${category}".
2. Strict Email Verification: For each candidate business you find, you MUST explicitly search for their verified public email address. Do Google search queries like:
   - "<business_name> <city> contact email"
   - "<business_name> faceoook email"
   - "<business_name> website email"
3. ZERO GUESSED EMAILS: You are STRICTLY FORBIDDEN from guessing email addresses. Do NOT concatenate "info@", "hello@", "contact@", "support@", "customercare@", etc. with their domain name just because you have the business name or website. Unless you verbatim see the email address in official search grounding/snippets, DO NOT return it.
4. Email Source URL: You must provide the exact Web page, social media listing (e.g. Facebook URL), or directory link where the email was found. If you cannot provide a real source, the lead is disqualified.
5. Quality Over Quota: If you can search but only find 1, 2, or 3 leads that have truly verified public emails, return only those leads. It is 1000x better to return only 1 lead with 100% correct, verified email than to return 4 leads where 1 or 2 are guessed/invalid. DO NOT satisfy the "4 leads" quota by inventing email addresses. If zero leads with verified emails are found, return an empty array [].

Return a JSON object matching this TypeScript interface:
{
  "leads": [
    {
      "business_name": "string (The real, registered, or public name of the business)",
      "category": "${category}",
      "city": "${city}",
      "website": "string (The actual URL, or empty string '' if they do NOT have a website)",
      "email": "string (MUST BE A 100% VERIFIED REAL EMAIL ADDRESS, NO DUMMY VALUES!)",
      "email_source_url": "string (The exact URL where you found this email to verify its existence)",
      "phone": "string (The real phone number if found, otherwise empty '')"
    }
  ]
}
`;

  const text = await generateAiContent(prompt, true);
  let rawJson = text || "{}";
  if (rawJson.includes("\`\`\`json")) {
    rawJson = rawJson.replace(/\`\`\`json/g, "").replace(/\`\`\`/g, "").trim();
  } else if (rawJson.includes("\`\`\`")) {
    rawJson = rawJson.replace(/\`\`\`/g, "").trim();
  }
  const parsed = JSON.parse(rawJson);
  const rawLeads: Lead[] = (parsed.leads || parsed) as Lead[];
  
  // Secondary validation step to ensure all emails are 100% valid and deliverable
  const validatedLeads: Lead[] = [];
  for (const lead of rawLeads) {
    if (lead.email) {
      const isValid = await verifyEmailDeliverability(lead.email);
      if (!isValid) {
        console.log(`⚠️ Secondary validation FAILED for ${lead.business_name}: "${lead.email}". Setting email to null/empty to prevent bounces.`);
        lead.email = null;
      } else {
        console.log(`✅ Secondary validation PASSED for ${lead.business_name}: "${lead.email}" (Email syntax and DNS resolve checked)`);
      }
    } else {
      lead.email = null;
    }
    validatedLeads.push(lead);
  }
  return validatedLeads;
}
